default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]
        stages:
          - pre-commit

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages:
          - pre-commit

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        stages:
          - pre-commit
